### ISSUE TITLE
Cant Use --gui On Windwows

### ISSUE THREAD

**Issue by Pinecone2** [epsylon/ufonet#106]
C:\Users\oldpi\Desktop\UfoNet\ufonet-master>python ufonet --gui

Traceback (most recent call last):
  File "ufonet", line 16, in <module>
    app.run()
  File "C:\Users\oldpi\Desktop\UfoNet\ufonet-master\core\main.py", line 810, in run
    self.create_web_interface()
  File "C:\Users\oldpi\Desktop\UfoNet\ufonet-master\core\main.py", line 1549, in create_web_interface
    from webgui import ClientThread
  File "C:\Users\oldpi\Desktop\UfoNet\ufonet-master\core\webgui.py", line 13, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher

Is There A Fix For This?

**Comment by epsylon** [comment]
"""
 ImportError: No module named Crypto.Cipher
"""
https://stackoverflow.com/questions/19623267/importerror-no-module-named-crypto-cipher
-----
"""
For Max/Win32 try:
pip uninstall pycrypto
easy_install pycrypto
"""
