### ISSUE TITLE
Problème à la vérification des zombies ! 

### ISSUE THREAD

**Issue by hadopiarelosers** [epsylon/ufonet#119]
Après avoir fait la commande ./ufonet --test-all : 

Error] - Something wrong testing ALL botnet status!

Traceback (most recent call last):
  File "/root/ufonet/core/main.py", line 701, in run
    test_all_botnet = self.testing_all()
  File "/root/ufonet/core/main.py", line 2680, in testing_all
    rpcs_ready, num_active_rpcs, num_failed_rpcs = self.testing_rpcs(rpcs)
  File "/root/ufonet/core/main.py", line 2491, in testing_rpcs
    rpc_vulnerable, rpc_pingback_url = self.search_rpc(rpc_host)
  File "/root/ufonet/core/main.py", line 2353, in search_rpc
    return rpc_vulnerable, rpc_pingback_url
UnboundLocalError: local variable 'rpc_pingback_url' referenced before assignment

**Comment by epsylon** [comment]
Under review: https://github.com/epsylon/ufonet/issues/118#issuecomment-413886965

**Comment by epsylon** [comment]
Fixed: https://github.com/epsylon/ufonet/commit/a19bb42a1ca9bfae3a364435b31b356e5c4e95e1
