### ISSUE TITLE
Error with testing Community Zombies

### ISSUE THREAD

**Issue by wripper** [epsylon/ufonet#12]
[Error] - Something wrong testing!

Traceback (most recent call last):
  File "/home/*user*/ufonet/ufonet/core/main.py", line 272, in run
    test = self.testing(zombies)
  File "/home/*user*/ufonet/ufonet/core/main.py", line 1917, in testing
    self.connect_zombies(zombie)
  File "/home/*user*/ufonet/ufonet/core/main.py", line 420, in connect_zombies
    t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

this is the error. i hope its not me :D

**Comment by epsylon** [comment]
check new release: v0.7 (Big Crunch) to see if this error is fixed on it...

**Comment by wripper** [comment]
I tested it again. Now its a bit better but after exactly 190 Attacks from the Zombie 'herd', it crashes every time i tried.

[Error] - Something wrong attacking!

Traceback (most recent call last):
  File "/home/user/ufonet/core/main.py", line 314, in run
    attack = self.attacking(zombies)
  File "/home/user/ufonet/core/main.py", line 2456, in attacking
    reply = self.injection(target, zombies)
  File "/home/user/ufonet/core/main.py", line 2669, in injection
    self.connect_zombies(zombie)
  File "/home/user/ufonet/core/main.py", line 450, in connect_zombies
    t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

**Comment by epsylon** [comment]
Again. This is not related with UFONet code.... 
It is a problem on how your OS is managing python threads. I tryed on the tool to reduce as max this issue, for example, giving to connections a timeout... I cannot reproducte this error on my box (Debian).
BTW, you can reduce the number of zombies... For what do you need 1000, if you can have 250 that makes 4 rounds? (250 x 4 = 1000 x 1). Try to decrease your list of zombies and will works..
UFONet is not a botnet related with have as much as possible zombies.. no... you only need some, but working correctly....

**Comment by wripper** [comment]
Okay thank u  :) i will try it. Good Job btw :D

**Comment by epsylon** [comment]
Thanks to you ;-)
I added this issue to FAQ; http://ufonet.03c8.net/FAQ.html
