### ISSUE TITLE
[Error] - Something wrong attacking!

### ISSUE THREAD

**Issue by tussy2625** [epsylon/ufonet#120]
hi, my attack fail with this error: 
Info] Flying some UCAV with 'heat-beam' weapons...

Traceback (most recent call last):
  File "/root/Desktop/ufonet/core/main.py", line 714, in run
[Error] UCAV: http://www.isitdownrightnow.com/ -> FAILED (cannot connect!)

[Error] - Something wrong attacking!

    attack = self.attacking(zombies)
  File "/root/Desktop/ufonet/core/main.py", line 2714, in attacking
    reply = self.injection(target, zombies)
  File "/root/Desktop/ufonet/core/main.py", line 2969, in injection
    check_is_up = self.check_is_up(target)
  File "/root/Desktop/ufonet/core/main.py", line 1980, in check_is_up
    if not "is down" or not "looks down" in target_reply: # parse external service for reply
UnboundLocalError: local variable 'target_reply' referenced before assignment
>>> 

im on the last version of ufonet and the lastest update of kali linux

**Comment by epsylon** [comment]
Thanks @tussy2625
Fixed: https://github.com/epsylon/ufonet/issues/120
