### ISSUE TITLE
cannot run test all on botnet

### ISSUE THREAD

**Issue by highm8** [epsylon/ufonet#122]
[Error] - Something wrong testing ALL botnet status!

Traceback (most recent call last):
  File "/root/Desktop/ufonet-master/core/main.py", line 701, in run
    test_all_botnet = self.testing_all()
  File "/root/Desktop/ufonet-master/core/main.py", line 2680, in testing_all
    zombies_ready, num_waiting_zombies, num_disconnected_zombies = self.testing(zombies)
  File "/root/Desktop/ufonet-master/core/main.py", line 2554, in testing
    reply = self.connect_zombies(zombie)
  File "/root/Desktop/ufonet-master/core/main.py", line 875, in connect_zombies
    t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
 help please

**Comment by epsylon** [comment]
This "issue" was ofently reported by users so the "solution" has been added to the FAQ. 
Please review it:
https://ufonet.03c8.net/FAQ.html
