### ISSUE TITLE
Zombies fail when attacking with extras

### ISSUE THREAD

**Issue by LulzRose** [epsylon/ufonet#131]
Whenever I try running this: sudo     ./ufonet -a http://www.SITENAMEHERE.org -r 1 --ufosyn 100 --loris 101 --loic 100 --db /PLACE -b "/PLACE"

Everything runs correctly but upon reaching the zombies I get this: 

[Error] - Something wrong attacking!

Traceback (most recent call last):
  File "/home/rose/ufonet/core/main.py", line 815, in run
    attack = self.attacking(zombies)
  File "/home/rose/ufonet/core/main.py", line 3006, in attacking
    reply = self.injection(target, zombies)
  File "/home/rose/ufonet/core/main.py", line 3268, in injection
    stress = self.stressing(target, zombie)
  File "/home/rose/ufonet/core/main.py", line 3076, in stressing
    req_reply = urllib2.urlopen(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>

**Comment by epsylon** [comment]
Isn't your target using https?
Which OS are you using?. Because some are having problems with SSL certs, as for example:
https://stackoverflow.com/questions/41691327/ssl-sslerror-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c
That can be solved by invoking this:
pip install --upgrade certifi
