### ISSUE TITLE
Issue starting GUI

### ISSUE THREAD

**Issue by Nekai** [epsylon/ufonet#150]
Warning: networking feature is disabled in Firejail configuration file
Switching to pid 6151, the first child process inside the sandbox
Child process initialized in 22.81 ms
Traceback (most recent call last):
  File "./ufonet", line 16, in <module>
    app.run()
  File "/home/nyseth/ufonet/core/main.py", line 1101, in run
    self.create_web_interface()
  File "/home/nyseth/ufonet/core/main.py", line 2075, in create_web_interface
    newthread = ClientThread(ip, port, clientsock)
  File "/home/nyseth/ufonet/core/webgui.py", line 37, in __init__
    self.pages = Pages()
  File "/home/nyseth/ufonet/core/webgui.py", line 1495, in __init__
    self.aspray = data["spray"]
KeyError: 'spray'
┌─[✗]─[nyseth@parrot]─[~/ufonet]
└──╼ $

**Comment by trollmad3** [comment]
What OS are you using?

**Comment by Nekai** [comment]
I simply re-git cloned the folder and it seemed to solve my issue

**Comment by trollmad3** [comment]
@Nekai That's great...can you close this issue now?

**Comment by epsylon** [comment]
@Nekai @trollmad3 I make it.
