### ISSUE TITLE
ImportError: No module named UFONet

### ISSUE THREAD

**Issue by TheYellinFrs** [epsylon/ufonet#181]
Traceback (most recent call last):
  File "/usr/local/bin/ufonet", line 11, in <module>
    load_entry_point('ufonet==1.2', 'gui_scripts', 'ufonet')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named UFONet
 

i installed it but it does not run

**Comment by TheYellinFrs** [comment]
what do i do now

**Comment by Aholicknight** [comment]
What was the command you used?

**Comment by epsylon** [comment]
@TheYellinFrs try to install it using "setup.py". Your path is incorrect, so 'main.py' cannot find correctly UFONet class on the code.
ex: **sudo python setup.py install**

**Comment by azamet90** [comment]
> @TheYellinFrs try to install it using "setup.py". Your path is incorrect, so 'main.py' cannot find correctly UFONet class on the code.
> ex: **sudo python setup.py install**

i have the same problem reinstalling not works pls check my posted error
