### ISSUE TITLE
ImportError: No module named UFONet

### ISSUE THREAD

**Issue by azamet90** [epsylon/ufonet#191]
```
sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to ufonet.egg-info/requires.txt
writing ufonet.egg-info/PKG-INFO
writing top-level names to ufonet.egg-info/top_level.txt
writing dependency_links to ufonet.egg-info/dependency_links.txt
writing entry points to ufonet.egg-info/entry_points.txt
reading manifest file 'ufonet.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ufonet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/core
copying build/lib.linux-x86_64-2.7/core/randomip.py -> build/bdist.linux-x86_64/egg/core
copying build/lib.linux-x86_64-2.7/core/herd.py -> build/bdist.linux-x86_64/egg/core
copying build/lib.linux-x86_64-2.7/core/ajaxmap.py -> build/bdist.linux-x86_64/egg/core
copying build/lib.linux-x86_64-2.7/core/webgui.py -> build/bdist.linux-x86_64/egg/core
copying build/lib.linux-x86_64-2.7/core/update.py -> build/bdist.linux-x86_64/egg/core
copying build/lib.linux-x86_64-2.7/core/__init__.py -> build/bdist.linux-x86_64/egg/core
copying build/lib.linux-x86_64-2.7/core/doll.py -> build/bdist.linux-x86_64/egg/core
copying build/lib.linux-x86_64-2.7/core/options.py -> build/bdist.linux-x86_64/egg/core
copying build/lib.linux-x86_64-2.7/core/main.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/tools
copying build/lib.linux-x86_64-2.7/core/tools/ufoscan.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib.linux-x86_64-2.7/core/tools/inspector.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib.linux-x86_64-2.7/core/tools/__init__.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib.linux-x86_64-2.7/core/tools/abductor.py -> build/bdist.linux-x86_64/egg/core/tools
copying build/lib.linux-x86_64-2.7/core/zombie.py -> build/bdist.linux-x86_64/egg/core
creating build/bdist.linux-x86_64/egg/core/images
copying build/lib.linux-x86_64-2.7/core/images/mothership.png -> build/bdist.linux-x86_64/egg/core/images
copying build/lib.linux-x86_64-2.7/core/images/favicon.ico -> build/bdist.linux-x86_64/egg/core/images
copying build/lib.linux-x86_64-2.7/core/images/commander.png -> build/bdist.linux-x86_64/egg/core/images
copying build/lib.linux-x86_64-2.7/core/images/board.png -> build/bdist.linux-x86_64/egg/core/images
creating build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib.linux-x86_64-2.7/core/images/aliens/alien1.png -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib.linux-x86_64-2.7/core/images/aliens/alien7.png -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib.linux-x86_64-2.7/core/images/aliens/alien4.png -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib.linux-x86_64-2.7/core/images/aliens/alien2.png -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib.linux-x86_64-2.7/core/images/aliens/alien5.png -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib.linux-x86_64-2.7/core/images/aliens/alien8.png -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib.linux-x86_64-2.7/core/images/aliens/alien6.png -> build/bdist.linux-x86_64/egg/core/images/aliens
copying build/lib.linux-x86_64-2.7/core/images/aliens/alien3.png -> build/bdist.linux-x86_64/egg/core/images/aliens
creating build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib.linux-x86_64-2.7/core/images/crew/link6.png -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib.linux-x86_64-2.7/core/images/crew/link2.png -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib.linux-x86_64-2.7/core/images/crew/link10.png -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib.linux-x86_64-2.7/core/images/crew/link5.png -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib.linux-x86_64-2.7/core/images/crew/link11.png -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib.linux-x86_64-2.7/core/images/crew/link9.png -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib.linux-x86_64-2.7/core/images/crew/link8.png -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib.linux-x86_64-2.7/core/images/crew/link1.png -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib.linux-x86_64-2.7/core/images/crew/link12.png -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib.linux-x86_64-2.7/core/images/crew/link3.png -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib.linux-x86_64-2.7/core/images/crew/link4.png -> build/bdist.linux-x86_64/egg/core/images/crew
copying build/lib.linux-x86_64-2.7/core/images/crew/link7.png -> build/bdist.linux-x86_64/egg/core/images/crew
creating build/bdist.linux-x86_64/egg/core/js
copying build/lib.linux-x86_64-2.7/core/js/raphael.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib.linux-x86_64-2.7/core/js/rlayer-src.js -> build/bdist.linux-x86_64/egg/core/js
creating build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib.linux-x86_64-2.7/core/js/cluster/MarkerCluster.Default.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib.linux-x86_64-2.7/core/js/cluster/leaflet.markercluster.js -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib.linux-x86_64-2.7/core/js/cluster/MarkerCluster.Default.ie.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib.linux-x86_64-2.7/core/js/cluster/leaflet.markercluster-src.js -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib.linux-x86_64-2.7/core/js/cluster/MarkerCluster.css -> build/bdist.linux-x86_64/egg/core/js/cluster
copying build/lib.linux-x86_64-2.7/core/js/ufo.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib.linux-x86_64-2.7/core/js/ufo-cloud.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib.linux-x86_64-2.7/core/js/style.css -> build/bdist.linux-x86_64/egg/core/js
copying build/lib.linux-x86_64-2.7/core/js/ajaxmap.css -> build/bdist.linux-x86_64/egg/core/js
creating build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib.linux-x86_64-2.7/core/js/leaflet/leaflet.js -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib.linux-x86_64-2.7/core/js/leaflet/leaflet.css -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib.linux-x86_64-2.7/core/js/leaflet/leaflet.ie.css -> build/bdist.linux-x86_64/egg/core/js/leaflet
creating build/bdist.linux-x86_64/egg/core/js/leaflet/images
copying build/lib.linux-x86_64-2.7/core/js/leaflet/images/marker-icon.png -> build/bdist.linux-x86_64/egg/core/js/leaflet/images
copying build/lib.linux-x86_64-2.7/core/js/leaflet/images/marker-shadow.png -> build/bdist.linux-x86_64/egg/core/js/leaflet/images
copying build/lib.linux-x86_64-2.7/core/js/leaflet/images/layers-2x.png -> build/bdist.linux-x86_64/egg/core/js/leaflet/images
copying build/lib.linux-x86_64-2.7/core/js/leaflet/images/ufonet-zombie.png -> build/bdist.linux-x86_64/egg/core/js/leaflet/images
copying build/lib.linux-x86_64-2.7/core/js/leaflet/images/marker-icon-2x.png -> build/bdist.linux-x86_64/egg/core/js/leaflet/images
copying build/lib.linux-x86_64-2.7/core/js/leaflet/images/layers.png -> build/bdist.linux-x86_64/egg/core/js/leaflet/images
copying build/lib.linux-x86_64-2.7/core/js/leaflet/leaflet-src.js -> build/bdist.linux-x86_64/egg/core/js/leaflet
copying build/lib.linux-x86_64-2.7/core/js/stars.js -> build/bdist.linux-x86_64/egg/core/js
copying build/lib.linux-x86_64-2.7/core/js/jquery-1.10.2.min.js -> build/bdist.linux-x86_64/egg/core/js
creating build/bdist.linux-x86_64/egg/core/txt
copying build/lib.linux-x86_64-2.7/core/txt/motherships.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib.linux-x86_64-2.7/core/txt/user-agents.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib.linux-x86_64-2.7/core/txt/misc.txt -> build/bdist.linux-x86_64/egg/core/txt
copying build/lib.linux-x86_64-2.7/core/txt/wafs.txt -> build/bdist.linux-x86_64/egg/core/txt
creating build/bdist.linux-x86_64/egg/core/mods
copying build/lib.linux-x86_64-2.7/core/mods/nuke.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib.linux-x86_64-2.7/core/mods/ufosyn.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib.linux-x86_64-2.7/core/mods/loris.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib.linux-x86_64-2.7/core/mods/spray.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib.linux-x86_64-2.7/core/mods/__init__.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib.linux-x86_64-2.7/core/mods/smurf.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib.linux-x86_64-2.7/core/mods/tachyon.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib.linux-x86_64-2.7/core/mods/xmas.py -> build/bdist.linux-x86_64/egg/core/mods
copying build/lib.linux-x86_64-2.7/core/mods/loic.py -> build/bdist.linux-x86_64/egg/core/mods
creating build/bdist.linux-x86_64/egg/server
copying build/lib.linux-x86_64-2.7/server/grider.txt -> build/bdist.linux-x86_64/egg/server
copying build/lib.linux-x86_64-2.7/server/missions.txt -> build/bdist.linux-x86_64/egg/server
copying build/lib.linux-x86_64-2.7/server/news.txt -> build/bdist.linux-x86_64/egg/server
copying build/lib.linux-x86_64-2.7/server/crypter.py -> build/bdist.linux-x86_64/egg/server
copying build/lib.linux-x86_64-2.7/server/wargames.txt -> build/bdist.linux-x86_64/egg/server
copying build/lib.linux-x86_64-2.7/server/grider.py -> build/bdist.linux-x86_64/egg/server
copying build/lib.linux-x86_64-2.7/server/blackhole.txt -> build/bdist.linux-x86_64/egg/server
copying build/lib.linux-x86_64-2.7/server/__init__.py -> build/bdist.linux-x86_64/egg/server
copying build/lib.linux-x86_64-2.7/server/nodes.dat -> build/bdist.linux-x86_64/egg/server
copying build/lib.linux-x86_64-2.7/server/board.txt -> build/bdist.linux-x86_64/egg/server
copying build/lib.linux-x86_64-2.7/server/blackhole.py -> build/bdist.linux-x86_64/egg/server
copying build/lib.linux-x86_64-2.7/server/grid.txt -> build/bdist.linux-x86_64/egg/server
byte-compiling build/bdist.linux-x86_64/egg/core/randomip.py to randomip.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/herd.py to herd.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/ajaxmap.py to ajaxmap.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/webgui.py to webgui.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/update.py to update.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/doll.py to doll.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/options.py to options.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/main.py to main.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/ufoscan.py to ufoscan.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/inspector.py to inspector.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/tools/abductor.py to abductor.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/zombie.py to zombie.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/nuke.py to nuke.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/ufosyn.py to ufosyn.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/loris.py to loris.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/spray.py to spray.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/smurf.py to smurf.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/tachyon.py to tachyon.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/xmas.py to xmas.pyc
byte-compiling build/bdist.linux-x86_64/egg/core/mods/loic.py to loic.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/crypter.py to crypter.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/grider.py to grider.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/server/blackhole.py to blackhole.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ufonet.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/ufonet-1.2-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ufonet-1.2-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/ufonet-1.2-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/ufonet-1.2-py2.7.egg
Extracting ufonet-1.2-py2.7.egg to /usr/local/lib/python2.7/dist-packages
ufonet 1.2 is already the active version in easy-install.pth
Installing ufonet script to /usr/local/bin
Installing ufonet script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/ufonet-1.2-py2.7.egg
Processing dependencies for ufonet==1.2
Searching for scapy==2.4.3
Best match: scapy 2.4.3
Adding scapy 2.4.3 to easy-install.pth file
Installing scapy script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Searching for requests==2.22.0
Best match: requests 2.22.0
Adding requests 2.22.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for python-whois==0.7.2
Best match: python-whois 0.7.2
Processing python_whois-0.7.2-py2.7.egg
python-whois 0.7.2 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/python_whois-0.7.2-py2.7.egg
Searching for pygeoip==0.3.2
Best match: pygeoip 0.3.2
Processing pygeoip-0.3.2-py2.7.egg
pygeoip 0.3.2 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/pygeoip-0.3.2-py2.7.egg
Searching for pydns==2.3.6
Best match: pydns 2.3.6
Processing pydns-2.3.6-py2.7.egg
pydns 2.3.6 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/pydns-2.3.6-py2.7.egg
Searching for pycurl==7.43.0.3
Best match: pycurl 7.43.0.3
Processing pycurl-7.43.0.3-py2.7-linux-x86_64.egg
pycurl 7.43.0.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/pycurl-7.43.0.3-py2.7-linux-x86_64.egg
Searching for pycrypto==2.6.1
Best match: pycrypto 2.6.1
Adding pycrypto 2.6.1 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for GeoIP==1.3.2
Best match: GeoIP 1.3.2
Processing GeoIP-1.3.2-py2.7-linux-x86_64.egg
GeoIP 1.3.2 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/GeoIP-1.3.2-py2.7-linux-x86_64.egg
Searching for future==0.16.0
Best match: future 0.16.0
Adding future 0.16.0 to easy-install.pth file
Installing pasteurize script to /usr/local/bin
Installing futurize script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for ufonet==1.2

```

```

sudo ufonet                                                                                                                                        
Traceback (most recent call last):
  File "/usr/local/bin/ufonet", line 11, in <module>
    load_entry_point('ufonet==1.2', 'gui_scripts', 'ufonet')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named UFONet

```

please help me to use it
another error
```
./ufonet --download-zombies                                                                                                                        
                                             0===============================================0
                                             ||                                             ||
                    (00)                     ||  * Botnet -> [DDoS]:                        ||
       (O)_  (O)   '----'   (O)  _(O)        ||      /Zombies : HTTP GET bots               ||
           |  |.''.( xx ).''.|  |            ||      /Droids  : HTTP GET (+params) bots     ||
           .'.'    |'..'|    '.'.            ||      /Aliens  : HTTP POST bots              ||
    .-.  .' /'--.__|_00_|__.--'\ '.  .-.     ||      /UCAVs   : Web Abusing bots            ||
   (O).)-|0|  \  x | ## |x   /  |0|-(.(O)    ||      /X-RPCs  : XML-RPC bots                ||
    `-'  '-'-._'-./ -00- \.-'_.-'-'  `-'     ||      /DBSTRESS: HTTP DB attack              ||
       _ | ||  '-.___||___.-'  || | _        ||      /SPRAY   : TCP-SYN reflector           ||
    .' _ | ||==O |   __   | O==|| | _ '.     ||      /SMURF   : ICMP echo flooder           ||
   / .' ''.|  || | /_00_\ | ||  |.'' '. \    ||      /TACHYON : DNS amplificator            ||
   | '###  |  =| | ###### | |=  |' ###  |    ||                                             ||
   | |(0)| '.  0\||__**_ ||/0  .' |(0)| |    ||  * Close Combat -> [DoS]:                   ||
   \ '._.'   '.  | \_##_/ |  .'   '._.' /    ||      /LOIC    : Fast HTTP requests          ||
    '.__ ____0_'.|__'--'__|.'_0____ __.'     ||      /LORIS   : Slow HTTP requests          ||
   .'_.-|                          |-._'.    ||      /UFOSYN  : TCP-SYN flooder             ||
                                             ||      /XMAS    : TCP-XMAS flooder            ||
   + Class: UFONet / ViPR404+ (model F) +    ||      /NUKE    : TCP-STARVATION attack       ||
                                             ||                                             ||
                                             0|=============================================|0

=========================================================================== 

888     888 8888888888 .d88888b.  888b    888          888    
888     888 888        d88P Y888b 8888b   888          888    
888     888 888       888     888 88888b  888          888    
888     888 8888888   888     888 888Y88b 888  .d88b.  888888 
888     888 888       888     888 888 Y88b888 d8P  Y8b 888    
888     888 888       888     888 888  Y88888 88888888 888    
Y88b. .d88P 888       Y88b. .d88P 888   Y8888 Y8b.     Y88b.  
 'Y88888P'  888        'Y88888P'  888    Y888  'Y8888   'Y8888

{(D)enial(OF)Fensive(S)ervice[ToolKit]}-{by_(io=psy+/03c8.net)} 

===========================================================================

[AI] Downloading list of [Zombies] from server ...

======================

[AI] Trying [Blackhole]: 176.28.23.46

[AI] [Control] [Blackhole] Reply: [VORTEX FAILED!]
------------

[Error] [AI] Unable to download list of [Zombies] from this [Blackhole] -> [Exiting!]
```

and the auto search is giving another error better to remove it ... since it is not updated for long time

**Comment by Aholicknight** [comment]
What linux distro are you using?

**Comment by azamet90** [comment]
> What linux distro are you using?

Hey! Thank you so much for answering. İm using kali linux 2019.4

**Comment by azamet90** [comment]
> What linux distro are you using?

i was thinking that you want to help but now i believe you was just wanting to know what distro im using huh :D

**Comment by azamet90** [comment]
@epsylon shiiiiiiit closed without even giving answer :D

**Comment by epsylon** [comment]
@azamet90 sorry I am a bit busy for this kind of "issues". Sure you can solve it reading/searching on the internet. ;-P

**Comment by Aholicknight** [comment]
@azamet90 you could search the problem on google and resolve it without needing our help.

**Comment by azamet90** [comment]
İ did actually research but... thanks... couldnt fix it

**Comment by azamet90** [comment]
and trying automatic search on internet for the bot is giving error too is this tool you mean still working or i need maybe windows subsystem to use it?

**Comment by azamet90** [comment]
after trying few times its working now but an update is needed because only on gui mode it is attacking and i will open post for this too because its new problem

**Comment by epsylon** [comment]
Your reports don't make sense:
https://github.com/epsylon/ufonet/issues/191
https://github.com/epsylon/ufonet/issues/192
Stop bothering to this forum or I will kick you out. Am I clear?

**Comment by azamet90** [comment]
i already gave my answer to this shit bb

**Comment by epsylon** [comment]
You can use this hash for donations: 19aXfJtoYJUoXEZtjNwsah2JKN9CK5Pcjw

**Comment by azamet90** [comment]
> You can use this hash for donations: 19aXfJtoYJUoXEZtjNwsah2JKN9CK5Pcjw

donations for what :D

**Comment by Aholicknight** [comment]
@azamet90 You are starting to piss off the creator of UFONet. Please find the issue you are having on google as you are not providing any helpful comments.

**Comment by lesscooler222** [comment]
Hi @azamet90

I know this is an old comment thread but running it with "python3 ufonet" should work for you (: 

(without the commas)

It's funny how the main dev of UFONet could write those two sentences claiming that he doesn't have time to answer the question you're asking when the answer was a lot simpler in comparison to what he wrote.

Good day mate!

**Comment by epsylon** [comment]
@lesscooler222 Try to understand me. The tool has 380 issues, of which more than 80% are the same, they contribute nothing, or simply show that whoever writes has not read anything. In addition to not using reporting template:

https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md

I give you an example (from other of the projects that I maintain) of how you can work better when you are a developer:

https://github.com/epsylon/xsser/issues/33
