### ISSUE TITLE
-inspect

### ISSUE THREAD

**Issue by indigopsy** [epsylon/ufonet#20]
no matter what web site i enter same error happens:
`./ufonet -i http://www.google.com`

```
Inspecting target to find the best place to attack... SSssh!

======================

Traceback (most recent call last):
  File "/git/botnets/ufonet/core/main.py", line 325, in run
    inspection = self.inspecting()
  File "/git/botnets/ufonet/core/main.py", line 926, in inspecting
    ctx = ssl.create_default_context() # creating context to bypass SSL cert validation (black magic)
AttributeError: 'module' object has no attribute 'create_default_context'

[Error] - Something wrong inspecting... Not any object found!

```

**Comment by epsylon** [comment]
Read this: https://github.com/epsylon/ufonet/issues/13#issuecomment-241490475
