### ISSUE TITLE
ASCII Error whenever I try running python3 ufonet?

### ISSUE THREAD

**Issue by trained** [epsylon/ufonet#209]
```
root@devilsden:~/ufonet# python3 ufonet
Traceback (most recent call last):
  File "ufonet", line 13, in <module>
    app = UFONet()
  File "/root/ufonet/core/main.py", line 79, in __init__
    self.mothership_baptism() # generating static name/id for your mothership ;-)
  File "/root/ufonet/core/main.py", line 144, in mothership_baptism
    motherships = f.readlines()
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 201: ordinal not in range(128)
root@devilsden:~/ufonet#
```
any fix?

**Comment by epsylon** [comment]
Should be fixed, after this commit: https://github.com/epsylon/ufonet/commit/d6117dd5cafa61454310ed4927e07adcf1c206db

**Comment by trained** [comment]
@epsylon Also setup.py does it too

**Comment by trained** [comment]
@epsylon also...

`root@devilsden:~/ufonet# python3 ./ufonet
Traceback (most recent call last):
  File "./ufonet", line 13, in <module>
    app = UFONet()
  File "/root/ufonet/core/main.py", line 81, in __init__
    self.mothership_baptism() # generating static name/id for your mothership ;-)
  File "/root/ufonet/core/main.py", line 146, in mothership_baptism
    motherships = f.readlines()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 201: ordinal not in range(128)
root@devilsden:~/ufonet#
`

**Comment by epsylon** [comment]
@trained Try to --update. Also, be sure that you have removed previous shipname.txt, located at: core/txt/
