### ISSUE TITLE
wtf ;-;

### ISSUE THREAD

**Issue by gubiMonster** [epsylon/ufonet#21]
Hi, I've error like that:
[Error] - Something wrong attacking!
 
Traceback (most recent call last):
  File "/home/gubi/ufonet/core/main.py", line 314, in run
    attack = self.attacking(zombies)
  File "/home/gubi/ufonet/core/main.py", line 2456, in attacking
    reply = self.injection(target, zombies)
  File "/home/gubi/ufonet/core/main.py", line 2669, in injection
    self.connect_zombies(zombie)
  File "/home/gubi/ufonet/core/main.py", line 450, in connect_zombies
    t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

How to fix it?

**Comment by epsylon** [comment]
Review FAQ (Error: can't start new thread): http://ufonet.03c8.net/FAQ.html
