### ISSUE TITLE
Failing to run ufonet through CLI with ufonet syntax

### ISSUE THREAD

**Issue by FabxBs** [epsylon/ufonet#226]
Traceback (most recent call last):
  File "/usr/local/bin/ufonet", line 11, in <module>
    load_entry_point('ufonet==1.4', 'gui_scripts', 'ufonet')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'UFONet'

**Comment by epsylon** [comment]
@FabxBs It seems that you have some path problems... Are you using any kind of pre-packaged UFONet version?. Because it looks wrong built.

You have an executable at: /usr/local/bin/ufonet, that cannot find main() function.

Try to review that and/or fixing it using, for example, soft-links..

**Comment by FabxBs** [comment]
I did a clone of your github repo directly, and then tried to install it with the python setup.

**Comment by FabxBs** [comment]
Ok i fixed, needed to write in CLI python3 ufonet --gui or python3 ufonet.
