### ISSUE TITLE
Cant open it

### ISSUE THREAD

**Issue by Nextgenthebear** [epsylon/ufonet#23]
Every time i go to where the file was extracted "cd /home/nextgen/Downloads/ufonet-v0.8/ " it works but then i try to do " ./ufonet " and it says "Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/nextgen/Downloads/ufonet-v0.8/core/main.py", line 10, in <module>
    import os, sys, re, traceback, random, time, threading, base64, socket, httplib, ssl, requests, string
ImportError: No module named requests "
Please help 
I am on Kubuntu another verison of Ubuntu

**Comment by Pr0xy671** [comment]
http://stackoverflow.com/questions/17309288/importerror-no-module-named-requests

**Comment by epsylon** [comment]
$ sudo pip install requests

**Comment by Nextgenthebear** [comment]
I ran " sudo pop install requests " and it downloaded and i still try to do " ./ufonet " and it says  " Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/nextgen/Downloads/ufonet-v0.8/core/main.py", line 16, in <module>
    from herd import Herd
  File "/home/nextgen/Downloads/ufonet-v0.8/core/herd.py", line 11, in <module>
    import zombie
  File "/home/nextgen/Downloads/ufonet-v0.8/core/zombie.py", line 10, in <module>
    import pycurl, StringIO, md5, re
ImportError: No module named pycurl "
