### ISSUE TITLE
Cryto?

### ISSUE THREAD

**Issue by shiaia** [epsylon/ufonet#237]
I try and use the web interface and I get this error. I've tried doing "pip install crypto"  but that didn't work. I've also tried using the setup.py but I get these errors https://pastebin.com/QehSpgrd 

Traceback (most recent call last):
  File "./ufonet", line 16, in <module>
    app.run()
  File "/home/shia/ufonet/core/main.py", line 1198, in run
    self.create_web_interface()
  File "/home/shia/ufonet/core/main.py", line 2729, in create_web_interface
    from .webgui import ClientThread
  File "/home/shia/ufonet/core/webgui.py", line 20, in <module>
    from core.tools.crypter import Cipher
  File "/home/shia/ufonet/core/tools/crypter.py", line 23, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by Aholicknight** [comment]
Enter the command `pip install pycryptodome==3.4.3` then try to use the web interface again.

**Comment by epsylon** [comment]
@shiaia **sudo apt-get install python3-crypto**
