### ISSUE TITLE
I have get error

### ISSUE THREAD

**Issue by zeeebbbrrraaa** [epsylon/ufonet#240]
root@kali:/# cd
root@kali:~# cd ufoney
bash: cd: ufoney: No such file or directory
root@kali:~# cd ufoney
bash: cd: ufoney: No such file or directory
root@kali:~# cd ufonet
root@kali:~/ufonet# python3 ufonet --gui

                                                0=============================================0
                                                ||                                           ||
   ||                                     ||    ||  * Botnet -> [DDoS]:                      ||
 -(00)-                                 -(00)-  ||      /Zombies : HTTP GET bots             ||
   ||                (00)                 ||    ||      /Droids  : HTTP GET (+params) bots   ||
        (O)_  (O)  0'----'0  (O)  _(O)          ||      /Aliens  : HTTP POST bots            ||
            |  |.''.( xx ).''.|  |              ||      /UCAVs   : Web Abusing bots          ||
            .'.'   X|'..'|X   '.'.              ||      /X-RPCs  : XML-RPC bots              ||
     .-.  .' /'--.__|_00_|__.--'\ '.  .-.       ||      /DBSTRESS: HTTP DB attack            ||
    (O).)-|0|  \   x| ## |x   /  |0|-(.(O)      ||      /SPRAY   : TCP-SYN reflector         ||
     `-'  '-'-._'-./ -00- \.-'_.-'-'  `-'       ||      /SMURF   : ICMP echo flooder         ||
        _ | ||  '-.___||___.-'  || | _          ||      /TACHYON : DNS amplificator          ||
     .' _ | ||==O |   __   | O==|| | _ '.       ||      /MONLIST : NTP amplificator          ||
    / .' ''.|  || | /_00_\ | ||  |.'' '. \      ||                                           ||
    | '###  |  =| | ###### | |=  |' ###  |      ||   * Close Combat -> [DoS]:                ||
    | |(0)| '.  0\||__**_ ||/0  .' |(0)| |      ||      /LOIC    : Fast HTTP requests        ||
    \ '._.'   '.  | \_##_/ |  .'   '._.' /      ||      /LORIS   : Slow HTTP requests        ||
     '.__ ____0_'.|__'--'__|.'_0____ __.'       ||      /UFOSYN  : TCP-SYN flooder           ||
    .'_.-|                          |-._'.      ||      /XMAS    : TCP-XMAS flooder          ||
                                                ||      /NUKE    : TCP-STARVATION attack     ||
    + Class: UFONet / ViPR404+ (model G) +      ||                                           ||
                                                0|===========================================|0

                                                0=============================================0
                                                ||                                           ||
   ||                                     ||    ||  * Botnet -> [DDoS]:                      ||
 -(00)-                                 -(00)-  ||      /Zombies : HTTP GET bots             ||
   ||                (00)                 ||    ||      /Droids  : HTTP GET (+params) bots   ||
        (O)_  (O)  0'----'0  (O)  _(O)          ||      /Aliens  : HTTP POST bots            ||
            |  |.''.( xx ).''.|  |              ||      /UCAVs   : Web Abusing bots          ||
            .'.'   X|'..'|X   '.'.              ||      /X-RPCs  : XML-RPC bots              ||
     .-.  .' /'--.__|_00_|__.--'\ '.  .-.       ||      /DBSTRESS: HTTP DB attack            ||
    (O).)-|0|  \   x| ## |x   /  |0|-(.(O)      ||      /SPRAY   : TCP-SYN reflector         ||
     `-'  '-'-._'-./ -00- \.-'_.-'-'  `-'       ||      /SMURF   : ICMP echo flooder         ||
        _ | ||  '-.___||___.-'  || | _          ||      /TACHYON : DNS amplificator          ||
     .' _ | ||==O |   __   | O==|| | _ '.       ||      /MONLIST : NTP amplificator          ||
    / .' ''.|  || | /_00_\ | ||  |.'' '. \      ||                                           ||
    | '###  |  =| | ###### | |=  |' ###  |      ||   * Close Combat -> [DoS]:                ||
    | |(0)| '.  0\||__**_ ||/0  .' |(0)| |      ||      /LOIC    : Fast HTTP requests        ||
    \ '._.'   '.  | \_##_/ |  .'   '._.' /      ||      /LORIS   : Slow HTTP requests        ||
     '.__ ____0_'.|__'--'__|.'_0____ __.'       ||      /UFOSYN  : TCP-SYN flooder           ||
    .'_.-|                          |-._'.      ||      /XMAS    : TCP-XMAS flooder          ||
                                                ||      /NUKE    : TCP-STARVATION attack     ||
    + Class: UFONet / ViPR404+ (model G) +      ||                                           ||
                                                0|===========================================|0

===========================================================================

888     888 8888888888 .d88888b.  888b    888          888
888     888 888        d88P Y888b 8888b   888          888
888     888 888       888     888 88888b  888          888
888     888 8888888   888     888 888Y88b 888  .d88b.  888888
888     888 888       888     888 888 Y88b888 d8P  Y8b 888
888     888 888       888     888 888  Y88888 88888888 888
Y88b. .d88P 888       Y88b. .d88P 888   Y8888 Y8b.     Y88b.
 'Y88888P'  888        'Y88888P'  888    Y888  'Y8888   'Y8888

{(D)enial(OF)Fensive(S)ervice[ToolKit]}-{by_(io=psy+/03c8.net)}

===========================================================================

[AI] Trying to update automatically to the latest stable version

[Info] [GitHub] Reply:

Already up to date.

[Info] [AI] Congratulations!! UFONet has been updated... ;-)

>>>

                                                0=============================================0
                                                ||                                           ||
   ||                                     ||    ||  * Botnet -> [DDoS]:                      ||
 -(00)-                                 -(00)-  ||      /Zombies : HTTP GET bots             ||
   ||                (00)                 ||    ||      /Droids  : HTTP GET (+params) bots   ||
        (O)_  (O)  0'----'0  (O)  _(O)          ||      /Aliens  : HTTP POST bots            ||
            |  |.''.( xx ).''.|  |              ||      /UCAVs   : Web Abusing bots          ||
            .'.'   X|'..'|X   '.'.              ||      /X-RPCs  : XML-RPC bots              ||
     .-.  .' /'--.__|_00_|__.--'\ '.  .-.       ||      /DBSTRESS: HTTP DB attack            ||
    (O).)-|0|  \   x| ## |x   /  |0|-(.(O)      ||      /SPRAY   : TCP-SYN reflector         ||
     `-'  '-'-._'-./ -00- \.-'_.-'-'  `-'       ||      /SMURF   : ICMP echo flooder         ||
        _ | ||  '-.___||___.-'  || | _          ||      /TACHYON : DNS amplificator          ||
     .' _ | ||==O |   __   | O==|| | _ '.       ||      /MONLIST : NTP amplificator          ||
    / .' ''.|  || | /_00_\ | ||  |.'' '. \      ||                                           ||
    | '###  |  =| | ###### | |=  |' ###  |      ||   * Close Combat -> [DoS]:                ||
    | |(0)| '.  0\||__**_ ||/0  .' |(0)| |      ||      /LOIC    : Fast HTTP requests        ||
    \ '._.'   '.  | \_##_/ |  .'   '._.' /      ||      /LORIS   : Slow HTTP requests        ||
     '.__ ____0_'.|__'--'__|.'_0____ __.'       ||      /UFOSYN  : TCP-SYN flooder           ||
    .'_.-|                          |-._'.      ||      /XMAS    : TCP-XMAS flooder          ||
                                                ||      /NUKE    : TCP-STARVATION attack     ||
    + Class: UFONet / ViPR404+ (model G) +      ||                                           ||
                                                0|===========================================|0

==========================================
Starting round: 1  of  1
==========================================
[Info] [Zombies] Attacking from: check-host.net
[Info] [Zombies] Attacking from: validator.w3.org
[Info] [Zombies] Attacking from: translate.google.com
[Info] [Zombies] Attacking from: www.babalweb.net
[Info] [Aliens] Attacking from: nibbler.silktide.com
[Info] [Droids] Attacking from: www.statscrop.com
[Info] [X-RPCs] Attacking from: www.acupeace.com
[Info] [Droids] Attacking from: www.textise.net
[Info] [X-RPCs] www.acupeace.com -> FAILED (cannot connect!)
[Info] [X-RPCs] Attacking from: www.sbc4d.com
[Info] [Aliens] Attacking from: www.site24x7.com
[Info] [Droids] Attacking from: www.openadmintools.com
[Info] [Aliens] www.site24x7.com -> FAILED (cannot connect!)
[Info] [Aliens] Attacking from: isitdown.co.uk
[Info] [Droids] Attacking from: sitecheck.sucuri.net
[Info] [Aliens] Attacking from: isitdown.co.uk
[Info] [Droids] Attacking from: www.sslshopper.com
[Info] [UCAVs] updowntoday.com -> Target is ONLINE! -> [Keep shooting!]
[Info] [Droids] Attacking from: www.whatsmydns.net
[Info] [Aliens] Attacking from: checkwebsiteonline.com
[Info] [Aliens] checkwebsiteonline.com -> FAILED (cannot connect!)
[Info] [Aliens] Attacking from: websitechecker.online
[Info] [Droids] Attacking from: gsnedders.html5.org
[Info] [UCAVs] www.isthissitedown.org -> Target is ONLINE! -> [Keep shooting!]
[Info] [Aliens] websitechecker.online -> FAILED (cannot connect!)
[Info] [Aliens] Attacking from: gtmetrix.com
[Info] [Droids] Attacking from: developers.google.com
[Info] [Droids] Attacking from: jigsaw.w3.org
[Info] [Aliens] Attacking from: wheresitup.com
[Info] [UCAVs] www.downforeveryoneorjustme.com -> Target is ONLINE! -> [Keep shooting!]
[Info] [UCAVs] downdetector.com -> Target is ONLINE! -> [Keep shooting!]
[Info] [UCAVs] website-down.com -> Target is ONLINE! -> [Keep shooting!]
[Info] [UCAVs] www.isitdownrightnow.com -> FAILED (cannot connect!)
[Info] [UCAVs] check-host.net -> Target is ONLINE! -> [Keep shooting!]
[Info] [Droids] Attacking from: www.htmlhelp.com
[Info] [UCAVs] isitup.org -> Target is ONLINE! -> [Keep shooting!]

==========================================
Herd statistics
==========================================
Zombie : http://check-host.net/check-http?host=  |  1  hits  0  fails  0  retries
  Times: 0:00:01.076846  total  0:00:01.076846  min  0:00:01.076846  avg  0:00:01.076846  max
  Sizes: 35.5KiB  total  35.5KiB  min  35.5KiB  avg  35.5KiB  max
---------------------
Zombie : https://validator.w3.org/nu/?doc=  |  1  hits  0  fails  0  retries   Times: 0:00:03.266162  total  0:00:03.266162  min  0:00:03.266162  avg  0:00:03.266162  max
  Sizes: 28.7KiB  total  28.7KiB  min  28.7KiB  avg  28.7KiB  max
---------------------
Zombie : http://translate.google.com/translate?u=  |  1  hits  0  fails  0  retries
  Times: 0:00:00.290125  total  0:00:00.290125  min  0:00:00.290125  avg  0:00:00.290125  max
  Sizes: 298.0KiB  total  298.0KiB  min  298.0KiB  avg  298.0KiB  max
---------------------
Zombie : http://www.babalweb.net/ar/open.php?url=  |  1  hits  0  fails  0  retries
  Times: 0:00:01.626173  total  0:00:01.626173  min  0:00:01.626173  avg  0:00:01.626173  max
  Sizes: 3.7KiB  total  3.7KiB  min  3.7KiB  avg  3.7KiB  max
---------------------
================================================================================
Zombie 0day:  http://check-host.net/check-http?host=  with  1  hits
================================================================================
Total invocations: 4 | Zombies: 4 | Hits: 4 | Fails: 0
Total time: 0:00:06.259306 | Avg time: 0:00:01.564827
Total size: 365.9KiB | Avg size: 91.5KiB
---------------------
==========================================
Troops statistics
==========================================
Aliens: 8 | Hits: 5 | Fails: 3
Droids: 12 | Hits: 11 | Fails: 1
X-RPCs: 56 | Hits: 2 | Fails: 4
UCAVs : 8 | Hits: 7 | Fails: 1
---------------------

=====================

[Info] [AI] Report completed! -> [Purging!]

=====================

[Info] [AI] [Control] You have [9] units that aren't working as expected...

 + Aliens : [3]
 + Droids : [1]
 + X-RPCs : [4]
 + UCAVs  : [1]

[Info] [AI] Purging failed units from files...

 + [Info] [Aliens] https://www.site24x7.com/check-website-availability.html;$POST;url -> [Purged!]
 + [Info] [Aliens] https://checkwebsiteonline.com/domain;$POST;url -> [Purged!]
 + [Info] [Aliens] https://websitechecker.online/test_url;$POST;url -> [Purged!]
 + [Info] [Droids] http://www.htmlhelp.com/cgi-bin/validate.cgi?url=$TARGET&warnings=yes&spider=yes -> [Purged!]
 + [Info] [X-RPCs] http://www.acupeace.com/xmlrpc.php -> [Purged!]
 + [Info] [X-RPCs] http://www.sbc4d.com/xmlrpc.php -> [Purged!]
 + [Info] [X-RPCs] http://wp.omni-tech.net/xmlrpc.php -> [Purged!]
 + [Info] [X-RPCs] http://104.236.21.36/xmlrpc.php -> [Purged!]
 + [Info] [UCAVs] https://www.isitdownrightnow.com/ -> [Purged!]

[Info] [AI] You have removed [88] units! -> [OK!]

---------------------

[AI] Generating random exit...

 -> Wisdom worries about being slow in his speeches and diligent in his actions...

>>>

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-102:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 54, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 2820, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-104:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 54, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 2820, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-105:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 54, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 2820, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-106:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 54, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 2820, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-107:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 54, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 2820, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-108:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 54, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 2820, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-109:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 54, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 2820, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-110:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 54, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 2820, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-111:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 54, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 2820, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-112:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 54, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 2820, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-113:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 54, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 2820, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-114:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 54, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 2820, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-115:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 54, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 2820, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

**Comment by epsylon** [comment]
@zeeebbbrrraaa terrible report... try it again.

**Comment by epsylon** [comment]
bug reporting template -> https://github.com/epsylon/ufonet/blob/master/docs/.github/ISSUE_TEMPLATE/bug_report.md
