### ISSUE TITLE
GUI Was working

### ISSUE THREAD

**Issue by ipaidthebills** [epsylon/ufonet#276]
Had no issues until today getting the GUI to run.
Loads up on the browser as "Unable to connect". Checked port 9999 and not in use by any other program.
Here is what comes up when I run the GUI.

Traceback (most recent call last):
  File "ufonet", line 16, in <module>
    app.run()
  File "/root/pentest/ufonet/core/main.py", line 1306, in run
    self.create_web_interface()
  File "/root/pentest/ufonet/core/main.py", line 3096, in create_web_interface
    newthread = ClientThread(ip, port, clientsock)
  File "/root/pentest/ufonet/core/webgui.py", line 59, in __init__
    self.pages = Pages()
  File "/root/pentest/ufonet/core/webgui.py", line 2640, in __init__
    self.afraggle = data["fraggle"]
KeyError: 'fraggle'

**Comment by epsylon** [comment]
@ipaidthebills this is related with the WebGUI json files, probably because is containing old stats data.
Try to **remove this file: ufonet/core/json/stats.json**
