### ISSUE TITLE
ERROR ON GUI

### ISSUE THREAD

**Issue by ictkmc01** [epsylon/ufonet#281]
python3 ./ufonet --gui
error:
Traceback (most recent call last):
  File "./ufonet", line 16, in <module>
    app.run()
  File "/home/ghostofcyber01/Desktop/H1/ufonet/core/main.py", line 1306, in run
    self.create_web_interface()
  File "/home/ghostofcyber01/Desktop/H1/ufonet/core/main.py", line 3092, in create_web_interface
    tcpsock.bind((host,port))
OSError: [Errno 98] Address already in use

**Comment by epsylon** [comment]
Hi @ictkmc01 
This error means that the GUI socket (listening at TCP port: 9999) is busy:
` OSError: [Errno 98] Address already in use`
Try to close it (killing the previous process, restarting PC, etc..) or to reconfigure your box if you have other tools using it...and it will work after that.
