### ISSUE TITLE
does not start

### ISSUE THREAD

**Issue by ice735** [epsylon/ufonet#283]
Traceback (most recent call last):
  File "/usr/local/bin/ufonet", line 11, in <module>
    load_entry_point('ufonet==1.6', 'gui_scripts', 'ufonet')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'UFONet'

**Comment by epsylon** [comment]
@ice735 You have ufonet installed at _/usr/local/bin/ufonet_. And when you run this executable, it looks that it cannot find the _core.py_ file which means that your installation is broken. 

Try to install it again by directly cloning the sources from some of the GiT repos or by using the script provided for that task: **python3 setup.py install**
