### ISSUE TITLE
Dependency not listed !

### ISSUE THREAD

**Issue by Thecakeisgit** [epsylon/ufonet#29]
I needed to install pycrypto with <code>pip install pycrypto</code>on Ubuntu 16.04.1, you should add a note behind your deps.
*NOTE: It's Ubuntu 16.04 Bash on Windows version*

**Comment by Thecakeisgit** [comment]
Here is the Traceback with <code>./ufonet --gui</code>
```
Traceback (most recent call last):
  File "./ufonet", line 16, in <module>
    app.run()
  File "/root/ufonet/core/main.py", line 458, in run
    self.create_web_interface()
  File "/root/ufonet/core/main.py", line 1069, in create_web_interface
    from webgui import ClientThread
  File "/root/ufonet/core/webgui.py", line 12, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
```

**Comment by epsylon** [comment]
Roger!

**Comment by epsylon** [comment]
Commit updating requeriments: https://github.com/epsylon/ufonet/commit/0172a823c36b619311cce6edaa7ba7f7688bc2f6
