### ISSUE TITLE
Error with GUI

### ISSUE THREAD

**Issue by MrBoudhain** [epsylon/ufonet#300]
Hi, i have a problem with crypto module, he is installed via pip3, i tried the other issues on this github but anything working, what can i do ?

Traceback (most recent call last):
  File "/home/kali/Desktop/ufonet/ufonet", line 16, in <module>
    app.run()
  File "/home/kali/Desktop/ufonet/core/main.py", line 1306, in run
    self.create_web_interface()
  File "/home/kali/Desktop/ufonet/core/main.py", line 3084, in create_web_interface
    from .webgui import ClientThread
  File "/home/kali/Desktop/ufonet/core/webgui.py", line 21, in <module>
    from core.tools.crypter import Cipher
  File "/home/kali/Desktop/ufonet/core/tools/crypter.py", line 23, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

Thanks a lot man

**Comment by epsylon** [comment]
@MrBoudhain -> https://github.com/epsylon/ufonet/issues/298#issuecomment-784050178
