### ISSUE TITLE
Error 13

### ISSUE THREAD

**Issue by dxnilx** [epsylon/ufonet#311]
Dear Epsylon,
I really need ur help 
when i try to open the gui there stands 
Traceback (most recent call last):
  File "/home/kali/Desktop/ufonet/./ufonet", line 16, in <module>
    app.run()
  File "/home/kali/Desktop/ufonet/core/main.py", line 346, in run
    self.start_ship_engine()
  File "/home/kali/Desktop/ufonet/core/main.py", line 330, in start_ship_engine
    self.update_flying_stats() # update flying time stats
  File "/home/kali/Desktop/ufonet/core/main.py", line 1515, in update_flying_stats
    stats_json_file = open(self.mothership_stats_file, "w+")
PermissionError: [Errno 13] Permission denied: 'core/json/stats.json'

and when i trz to open the gui as root there stands that u cant open firefox in root
pleasee help me i am new to kali linux .

your Fan 

dxnilx

**Comment by dxnilx** [comment]
Dear Epsylon ,
I just saw antoher guz with the same problem an you said to him that he needs to delete the stats folder with this command 
rm -r core/json/ i did that aswell and it worked i thank you very much .I wish you the best.

Dxnilx
