### ISSUE TITLE
When I type python3 ufonet --gui this error happens

### ISSUE THREAD

**Issue by MrDoodle01** [epsylon/ufonet#316]
Traceback (most recent call last):
  File "/home/kali/ufonet/ufonet", line 16, in <module>
    app.run()
  File "/home/kali/ufonet/core/main.py", line 1306, in run
    self.create_web_interface()
  File "/home/kali/ufonet/core/main.py", line 3084, in create_web_interface
    from .webgui import ClientThread
  File "/home/kali/ufonet/core/webgui.py", line 21, in <module>
    from core.tools.crypter import Cipher
  File "/home/kali/ufonet/core/tools/crypter.py", line 23, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by epsylon** [comment]
@MrDoodle01 try to read/search about the error, first: _ModuleNotFoundError: No module named 'Crypto'_, so you don't make the others to waste their time...

0) **https://ufonet.03c8.net/#installation**

---------
Solutions:

a) **sudo apt-get install python3-crypto**
b) **pip3 install pycrypto**
