### ISSUE TITLE
Can activate receiving following error

### ISSUE THREAD

**Issue by lunahack** [epsylon/ufonet#32]
Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/root/Desktop/ufonet-v0.8/ufonet-v0.8/core/main.py", line 10, in <module>
    import os, sys, re, traceback, random, time, threading, base64, socket, httplib, ssl, requests, string
  File "/usr/local/lib/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl

**Comment by epsylon** [comment]
http://stackoverflow.com/questions/5128845/importerror-no-module-named-ssl
