### ISSUE TITLE
Error: Cant start new thread

### ISSUE THREAD

**Issue by ProXyy44** [epsylon/ufonet#33]
When i try to test the zombies i get this

[Error] - Something wrong testing!

Traceback (most recent call last):
  File "/root/ufonet/core/main.py", line 362, in run
    test = self.testing(zombies)
  File "/root/ufonet/core/main.py", line 1898, in testing
    reply = self.connect_zombies(zombie)
  File "/root/ufonet/core/main.py", line 523, in connect_zombies
    t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
Segmentation fault

Halp plz?

**Comment by epsylon** [comment]
http://ufonet.03c8.net/FAQ.html
