### ISSUE TITLE
What can i do by this... 

### ISSUE THREAD

**Issue by Warhammar** [epsylon/ufonet#360]
[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-5821:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 64, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 4057, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

**Comment by epsylon** [comment]
@Warhammar something wrong with your "Zombies" list. Looks that your list is empty. Check it.
