### ISSUE TITLE
Botnet gets everytime Stuck on 137 zombie

### ISSUE THREAD

**Issue by Warhammar** [epsylon/ufonet#361]
![Ufonetguihangup](https://user-images.githubusercontent.com/72944862/143047741-97e05c7e-c1f0-4675-b5ba-0c61e0b4f402.png)

The bot gets all the time Stuck on this.. 
Why..

Failurecode:

xception in thread Thread-34198:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 64, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 4057, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-34200:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 64, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 4057, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-34201:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 64, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 4057, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-34202:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 64, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 4057, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-34203:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 64, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 4057, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-34204:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 64, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 4057, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-34205:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 64, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 4057, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in self.zombies:
TypeError: argument of type 'NoneType' is not iterable

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]

[Error] [AI] You haven't [Zombies] to be extracted from: 'botnet/zombies.txt' -> [Aborting!]

[Info] [AI] [Control] Cannot retrieve [Aliens] from: 'botnet/aliens.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [Droids] from: 'botnet/droids.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [UCAVs] from: 'botnet/ucavs.txt' -> [Discarding!]
[Info] [AI] [Control] Cannot retrieve [X-RPCs] from: 'botnet/rpcs.txt' -> [Discarding!]
Exception in thread Thread-34207:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/root/ufonet/core/webgui.py", line 64, in run
    res = self.pages.get(req)
  File "/root/ufonet/core/webgui.py", line 4057, in get
    self.pages[page] = AjaxMap().ajax(pGet)
  File "/root/ufonet/core/ajaxmap.py", line 235, in ajax
    nzn=self.get_next_zombie(zn)
  File "/root/ufonet/core/ajaxmap.py", line 201, in get_next_zombie
    if name in se

**Comment by epsylon** [comment]
@Warhammar re-generate/re-make your zombies list and try it again
