### ISSUE TITLE
help Me plz 

### ISSUE THREAD

**Issue by discordbot234556789** [epsylon/ufonet#370]
Traceback (most recent call last):
  File "/usr/local/bin/ufonet", line 33, in <module>
    sys.exit(load_entry_point('ufonet==1.7', 'gui_scripts', 'ufonet')())
  File "/usr/local/bin/ufonet", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'UFONet'

**Comment by epsylon** [comment]
@discordbot234556789 something goes wrong with your environment path to UFONet executable: _"/usr/local/bin/ufonet"_

You can try this:

1. > clone UFONet code into a folder
2. > run: _python3 ufonet_ from it
