### ISSUE TITLE
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by BoBeR182** [epsylon/ufonet#390]
https://peps.python.org/pep-0353/
https://bugs.python.org/issue40943

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/user/ufonet/core/webgui.py", line 66, in run
    res = self.pages.get(req)
  File "/home/user/ufonet/core/webgui.py", line 7777, in get
    self.decrypt(globalnet_deckey, globalnet_owner)
  File "/home/user/ufonet/core/webgui.py", line 547, in decrypt
    aes = AES.new(cipher_key, mode, iv)
  File "/home/user/ufonet/lib/python3.10/site-packages/pycrypto-2.6.1-py3.10-linux-x86_64.egg/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/home/user/ufonet/lib/python3.10/site-packages/pycrypto-2.6.1-py3.10-linux-x86_64.egg/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/home/user/ufonet/lib/python3.10/site-packages/pycrypto-2.6.1-py3.10-linux-x86_64.egg/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

**Comment by epsylon** [comment]
related: https://stackoverflow.com/questions/70705404/systemerror-py-ssize-t-clean-macro-must-be-defined-for-formats
