### ISSUE TITLE
ufonet module acting really strange after basic install... ModuleNotFoundError: "UFOnet" ?

### ISSUE THREAD

**Issue by vlibNull** [epsylon/ufonet#399]
Yeah,... Pretty sure the subject line says it all but:
-python setup.py -- Doesn't work ( It finishes without errors, but upon ufonet command, it spits out the ModuleNotFoundError: UFOnet )
-python setup.py install -- Doesn't work. ( It finishes without errors, but upon ufonet command, it spits out the ModuleNotFoundError: UFOnet )
I have installed every dep, I have python2 and python (def to python3)

Current output of " ufonet " after install:

```
Traceback (most recent call last):
File "/usr/bin/ufonet", line 33, in <module>
sys.exit(load_entry_point('ufonet==1.8', 'gui_scripts', 'ufonet')())
File "/usr/bin/ufonet", line 25, in importlib_load_entry_point
return next(matches).load()
File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
module = import_module(match.group('module'))
File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'UFONet'
```

**Comment by vlibNull** [comment]
Just a note since I totally spaced it: I did run the installer as sudo.

**Comment by epsylon** [comment]
`ModuleNotFoundError: No module named 'UFONet'`

related: https://github.com/epsylon/ufonet/issues/398#issuecomment-1125387808
