### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by epeymenn** [epsylon/ufonet#402]
──(root㉿kali)-[~/ufonet]
└─# ufonet 
Traceback (most recent call last):
  File "/usr/local/bin/ufonet", line 33, in <module>
    sys.exit(load_entry_point('ufonet==1.8', 'gui_scripts', 'ufonet')())
  File "/usr/local/bin/ufonet", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'UFONet

**Comment by epsylon** [comment]
@epeymenn something wrong at your OS environment. I recommend that you **clone the repository again**.

**Comment by epsylon** [comment]
related: https://github.com/epsylon/ufonet/issues/398#issuecomment-1125387808
