### ISSUE TITLE
ModuleNotFoundError: No module named 'UFONet'

### ISSUE THREAD

**Issue by Kirill020708** [epsylon/ufonet#403]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/ufonet", line 33, in <module>
    sys.exit(load_entry_point('ufonet==1.8', 'gui_scripts', 'ufonet')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/ufonet", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'UFONet'

sudo python3 setup.py install

**Comment by epsylon** [comment]
related: https://github.com/epsylon/ufonet/issues/402
