### ISSUE TITLE
Exception in thread Thread-7

### ISSUE THREAD

**Issue by sinaj2889** [epsylon/ufonet#409]
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/files/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/files/home/ufonet/core/webgui.py", line 66, in run
    res = self.pages.get(req)
  File "/files/home/ufonet/core/webgui.py", line 7771, in get
    f = open("/tmp/out", "w")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/out'

**Comment by epsylon** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/out' -> the file doesn't exists and should be created next time you run the tool. Also you can "touch" it (touch /tmp/out) to have a new one and solve this.

**Comment by epsylon** [comment]
related: https://github.com/epsylon/ufonet/issues/406#issuecomment-1185403021
