### ISSUE TITLE
Parsing error cannot run the c&c

### ISSUE THREAD

**Issue by MiChaelinzo** [epsylon/ufonet#418]
```
  michael@Raze:~/BOTNET/ufonet$ sudo python3 ufonet --gui
Traceback (most recent call last):
  File "/home/michael/BOTNET/ufonet/ufonet", line 14, in <module>
    options = app.create_options()
  File "/home/michael/BOTNET/ufonet/core/main.py", line 208, in create_options
    self.optionParser = UFONetOptions()
  File "/home/michael/BOTNET/ufonet/core/options.py", line 28, in __init__
    self.zombies = int(self.extract_zombies())
ValueError: invalid literal for int() with base 10: 'broken!'

```

**Comment by epsylon** [comment]
@MiChaelinzo it looks that you have removed "botnet/zombies.txt" file. Try to restore it (ex: touch "botnet/zombies.txt").
