### ISSUE TITLE
Crypto module

### ISSUE THREAD

**Issue by newoneb** [epsylon/ufonet#436]
I downloaded ufonet from https://sourceforge.net/projects/ufonet/ . When I opened the terminal in ufonet folder, and typed in ./ufonet -help I got this:

```
/ufonet -help
/home/kali/Desktop/ufonet/core/main.py:3170: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if abductions_reply is not "":
/home/kali/Desktop/ufonet/core/main.py:3181: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if robots_reply is not "":
/home/kali/Desktop/ufonet/core/main.py:3192: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if troops_reply is not "":
/home/kali/Desktop/ufonet/core/main.py:3203: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if drones_reply is not "":
/home/kali/Desktop/ufonet/core/main.py:3214: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if reflectors_reply is not "":
/home/kali/Desktop/ufonet/core/main.py:3225: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if crystals_reply is not "":
/home/kali/Desktop/ufonet/core/main.py:3236: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if warps_reply is not "":
/home/kali/Desktop/ufonet/core/main.py:3247: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if bosons_reply is not "":
Traceback (most recent call last):
  File "/home/kali/Desktop/ufonet/./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/kali/Desktop/ufonet/core/main.py", line 14, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by newoneb** [comment]
BTW:
sudo apt-get install python3-crypto:
```
└─$ sudo apt-get install python3-crypto
[sudo] password for kali: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python3-crypto is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-crypto' has no installation candidate
```

**Comment by newoneb** [comment]
I also did 
sudo apt-get remove python3-pycrypto and python3-crypto
I did install pycryptodome

**Comment by epsylon** [comment]
@newoneb you are **not using the latest version of the tool**. Try to clone it from here.

also your OS environment is not correctly configurated. Try to upgrade it (**1400 not upgraded**).

**Comment by newoneb** [comment]
Hey, @epsylon !
I have installed a completely new machine (2023.1 v). 
On this machine, I've got nothing to upgrade: ```0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.```
So I downloaded ufonet from here using git command, but still it has the Crypto module issues:
```
┌──(kali㉿kali)-[~]
└─$ git clone https://github.com/epsylon/ufonet
Cloning into 'ufonet'...
remote: Enumerating objects: 918, done.
remote: Counting objects: 100% (119/119), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 918 (delta 65), reused 97 (delta 62), pack-reused 799
Receiving objects: 100% (918/918), 17.16 MiB | 9.69 MiB/s, done.
Resolving deltas: 100% (444/444), done.
                                                                             
┌──(kali㉿kali)-[~]
└─$ python ufonet --help
/usr/bin/python: can't find '__main__' module in '/home/kali/ufonet'
                                                                             
┌──(kali㉿kali)-[~]
└─$ cd '/home/kali/ufonet' 
                                                                             
┌──(kali㉿kali)-[~/ufonet]
└─$ python ufonet --help
Traceback (most recent call last):
  File "/home/kali/ufonet/ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/kali/ufonet/core/main.py", line 14, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
                                                    
                                                   ```

**Comment by newoneb** [comment]
Actually, nevermind, after 

```
