### ISSUE TITLE
Cannot complete round. Errors. 

### ISSUE THREAD

**Issue by worm99** [epsylon/ufonet#45]
When running a round it goes about a few mintes and then gets the following: 

[Error] - Something wrong attacking!
```

Traceback (most recent call last):
  File "/home/user/ufonet/core/main.py", line 386, in run
    attack = self.attacking(zombies)
  File "/home/user/ufonet/core/main.py", line 2022, in attacking
    reply = self.injection(target, zombies)
  File "/home/user/ufonet/core/main.py", line 2234, in injection
    self.connect_zombies(zombie)
  File "/home/user/ufonet/core/main.py", line 523, in connect_zombies
    t.start()
  File "/usr/lib/python2.7/threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
```

**Comment by Tosible** [comment]
http://ufonet.03c8.net/FAQ.html

Try updating and optimizing your zombie list
