### ISSUE TITLE
UFONET ERROR

### ISSUE THREAD

**Issue by mike21cm** [epsylon/ufonet#464]
I am on kali linux 2023.4
I installed ufonet when I tried
Sudo ./ufonet it gave me this error 

Traceback (most recent call last):
  File "/home/kali/Desktop/ufonet/./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/kali/Desktop/ufonet/core/main.py", line 14, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by epsylon** [comment]
related: https://stackoverflow.com/questions/28355385/ddg#58077717
