### ISSUE TITLE
problem with crypto

### ISSUE THREAD

**Issue by zjuvee** [epsylon/ufonet#467]
When I run the command ./ufonet --gui I get this error

Traceback (most recent call last):
  File "/home/user/ufonet/./ufonet", line 16, in <module>
    app.run()
  File "/home/user/ufonet/core/main.py", line 1377, in run
    self.create_web_interface()
  File "/home/user/ufonet/core/main.py", line 3770, in create_web_interface
    from .webgui import ClientThread
  File "/home/user/ufonet/core/webgui.py", line 21, in <module>
    from core.tools.crypter import Cipher
  File "/home/user/ufonet/core/tools/crypter.py", line 23, in <module>
    from Crypto.Cipher import AES
  File "/usr/local/lib/python3.11/dist-packages/Crypto/Cipher/__init__.py", line 82, in <module>
    from Crypto.Cipher._mode_ctr import _create_ctr_cipher
  File "/usr/local/lib/python3.11/dist-packages/Crypto/Cipher/_mode_ctr.py", line 35, in <module>
    from Crypto.Util.number import long_to_bytes
  File "/usr/local/lib/python3.11/dist-packages/Crypto/Util/number.py", line 398
    s = pack('>I', n & 0xffffffffL) + s
                                ^
SyntaxError: invalid hexadecimal literal

**Comment by Freer10otp** [comment]
https://stackoverflow.com/questions/28355385/importerror-no-module-named-crypto

Section 16
