### ISSUE TITLE
Error SyntaxError: multiple exception types must be parenthesized

### ISSUE THREAD

**Issue by anonimusman00** [epsylon/ufonet#470]
> Traceback (most recent call last):
  File "/home/id/ufonet/./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/id/ufonet/core/main.py", line 14, in <module>
    from Crypto.Cipher import AES
  File "/usr/local/lib/python3.11/dist-packages/Crypto/Cipher/__init__.py", line 3, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/local/lib/python3.11/dist-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/local/lib/python3.11/dist-packages/Crypto/Util/_raw_api.py", line 256
    except OSError, exp:
           ^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

> 

I run "python3 ufonet" and get this.Please help me how to fix this error

**Comment by epsylon** [comment]
should be fixed at this release: https://github.com/epsylon/ufonet/commit/aea21b3c4a8fd2f5aa8c924afa4e96eb455a4e43

try this steps:

1. git clone https://github.com/epsylon/ufonet (or python3 **ufonet --update**)
2. cd ufonet
3. sudo python3 setup.py
4. python3 ufonet
