### ISSUE TITLE
error something went wrong testing, help!

### ISSUE THREAD

**Issue by bward11** [epsylon/ufonet#66]
im trying to test my zombies but every time i type the command: ./ufonet -t botnet/zombies.txt    i get an error saying: 
[Error] - Something wrong testing!

Traceback (most recent call last):
  File "/root/ufonet/core/main.py", line 367, in run
   test = self.testing(zombies)
 File "/root/ufonet/core/main.py", line 1898, in testing
   reply = self.connect_zombies(zombie)
  File "/root/ufonet/core/main.py", line 523, in connect_zombies
   t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
     _start_new_thread(self.__bootstrap, ())
error: can't start new thread

here is a picture!

![img_20170417_203112311](https://cloud.githubusercontent.com/assets/26526528/25101775/7e4a9704-23ad-11e7-855f-aac94f3b33bc.jpg)

**Comment by epsylon** [comment]
I need more info about your issue: Python version, SO, UFONet version, etc..
