### ISSUE TITLE
Error Self test zombie

### ISSUE THREAD

**Issue by Zaiakf** [epsylon/ufonet#75]
Error] - Something wrong testing!

Traceback (most recent call last):
  File "/home/kirhyn/ufonet/core/main.py", line 383, in run
    test = self.testing(zombies)
  File "/home/kirhyn/ufonet/core/main.py", line 2092, in testing
    reply = self.connect_zombies(zombie)
  File "/home/kirhyn/ufonet/core/main.py", line 570, in connect_zombies
    t.start()
  File "/usr/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
Segmentation fault

**Comment by epsylon** [comment]
You have some info about this error at FAQ: https://ufonet.03c8.net/FAQ.html
