### ISSUE TITLE
Hello, i have a problem

### ISSUE THREAD

**Issue by KekoShade** [epsylon/ufonet#81]
You should use google translator. Spanish.

Bueno, el tema es que me aparece todo esto en terminal(cmd)

./ufonet
Traceback (most recent call last):
  File "./ufonet", line 10, in <module>
    from core.main import UFONet
  File "/home/keko/Descargas/ufonet-master/core/main.py", line 16, in <module>
    from herd import Herd
  File "/home/keko/Descargas/ufonet-master/core/herd.py", line 11, in <module>
    import zombie
  File "/home/keko/Descargas/ufonet-master/core/zombie.py", line 10, in <module>
    import pycurl, StringIO, md5, re
ImportError: No module named pycurl

Si, ya he puesto todos los comandos para tener pycurl y las demas, pero me sigue dando error. Gracias!

**Comment by Tosible** [comment]
Do ```pip install pycurl```

**Comment by epsylon** [comment]
También puedes lanzar:
sudo apt-get install python-pycurl
